resources:
- manager.yaml
- component_versions.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - controller_manager_config.yaml
  name: manager-config

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: controller
  newName: caapm/kubernetes-operator
  newTag: latest

patches:
- path: patches.yaml
  target:
    kind: Deployment
